# Generated by Django 4.2.4 on 2023-10-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
    ]
