# Generated by Django 4.2.4 on 2023-09-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_commission_lessons_document_alter_lessons_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
