# Generated by Django 4.2.4 on 2023-09-22 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courses_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_program',
        ),
    ]
