# Generated by Django 4.2.4 on 2023-09-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_modulerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulerating',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
