# Generated by Django 4.2.4 on 2023-09-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_modulerating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulerating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
