# Generated by Django 4.2.4 on 2023-09-29 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_matricula_last_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='lessons_viewed',
            field=models.ManyToManyField(blank=True, related_name='matriculas_viewed', to='courses.lessons'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='last_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_lesson_for_matricula', to='courses.lessons'),
        ),
    ]
