# Generated by Django 4.2.4 on 2023-10-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_lessons_class_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='base_cert',
            field=models.ImageField(default='base_cert.png', upload_to='base_cert'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='cert_emited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matricula',
            name='date_cert_emited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='name_cert',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
