# Generated by Django 4.2.4 on 2023-10-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_commission_base_cert_matricula_cert_emited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
    ]
