# Generated by Django 4.2.4 on 2023-11-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_exam_alter_matricula_slug_question_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=400),
        ),
    ]
