# Generated by Django 4.2.4 on 2023-11-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_exam_name_alter_option_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
