# Generated by Django 4.2.4 on 2023-11-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_remove_lessons_pdf_lessons_link_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='link_pdf',
            field=models.URLField(blank=True, null=True),
        ),
    ]
