# Generated by Django 4.2.4 on 2023-11-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_remove_lessons_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs'),
        ),
    ]
