# Generated by Django 4.2.4 on 2023-11-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_lessons_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='visible',
            field=models.BooleanField(default='False'),
        ),
    ]
