# Generated by Django 4.2.4 on 2023-11-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_matricula_approved_studentexamattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='exam_percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
