# Generated by Django 4.2.4 on 2023-12-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_questionsandanswers_a1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsandanswers',
            name='a1',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='questionsandanswers',
            name='a10',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='questionsandanswers',
            name='a2',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='questionsandanswers',
            name='a3',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='questionsandanswers',
            name='a4',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='questionsandanswers',
            name='a5',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='questionsandanswers',
            name='a6',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='questionsandanswers',
            name='a7',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='questionsandanswers',
            name='a8',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='questionsandanswers',
            name='a9',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
