# Generated by Django 4.2.4 on 2023-12-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_questionsandanswers_a1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='day_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='link_zoom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='zoom',
            field=models.BooleanField(default=False),
        ),
    ]
