# Generated by Django 4.2.4 on 2023-12-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_lessons_day_time_lessons_link_zoom_lessons_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='status',
            field=models.CharField(default='', max_length=1),
        ),
    ]
